# Generated by Erlang.mk. Edit at your own risk!

ERTS_INCLUDE_DIR ?= /opt/erlang_22.1/lib/erlang/erts-10.5/include/
ERL_INTERFACE_INCLUDE_DIR ?= /opt/erlang_22.1/lib/erlang/lib/erl_interface-3.13/include
ERL_INTERFACE_LIB_DIR ?= /opt/erlang_22.1/lib/erlang/lib/erl_interface-3.13/lib
ERTS_DIR ?= /opt/erlang_22.1/lib/erlang/lib/erts-10.5
